### ISSUE TITLE
Making the results easier to work with

### ISSUE THREAD

**Issue by FBumann** [flixOpt/flixOpt#19]
Currently, it's hard to distinguish between parameters that are set by the user, and results of optimization variables.
This should be improved by redesigning the structure of flix_results.

**Comment by FBumann** [comment]
## Content:

### Operation:
- val (power per time step)
- all effects the flow/comp contributed to
- _predefined_:
  - lower and upper bound of operation (
  - all effect parameters (costs_per_flow_hour, ...)
 
### Invest:
- nominal_val, if invest
- all effects the flow/comp contributed to (with invest)
- _predefined_:
  - invest parameters (with bounds)

**Comment by FBumann** [comment]
Effect Results should be available as time series for every component.

**Comment by baumbude** [comment]
> Effect Results should be available as time series for every component.

Problem: benötigt viele zusätzliche Variablen im Solver-Modell. Wenn wir ganz sicher sind, dass pyomo und highs inzwischen keine Probleme bekommen mit sehr großen Variablenmengen, dann können wir das auch als Zwischenvariablen in das Modell einbauen. Ich hatte dazu auch nochmal recherchiert: Es gibt anscheinend keine pyomo-Alternativen, die ein presolving machen VOR dem presolving des solvers. Denn dann wäre es ganz sicher kein Problem, weil das an den Solver übergebene Problem dann wieder so klein ist wie ohne Zwischenvariablen.

**Comment by FBumann** [comment]
Closed with #53
