### ISSUE TITLE
Improve tests and add folder for unit tests

### ISSUE THREAD

**Issue by baumbude** [flixOpt/flixOpt#37]

**Comment by FBumann** [comment]
Das Beispiel läuft bei mir.

Wie ich sehe hast du eifach nur die Pfadkorrektur raus genommen.

Ich hab das mal in meinen dev-tests Branch übernommen. Da hab ich jetzt die examples in echte tests überführt. Die können wir jetzt so anpassen, dass Sie gezielt einzelne features o.ä. testen.

Das ganze läuft auch mit pytest.
Bitte gib mir auch mal Rückmeldung ob die teste bei dir laufen.
Im file "run_all_test.py" siehts jetzt genauso aus wie in deinem Beispiel, sollte also gehen.

**Comment by FBumann** [comment]
Ich habe mit peter auch gestern zu dem Thema gesprochen: Eine Trennung von Examples und tests ist früher oder später ohnehin notwendig.
Des ermöglicht, dass Tests kompakt und funktional geschriben werden können Auch ein modularer Aufbau ist möglich.
Examples wiederum können umfangreich dokumentiert und Einfach verständlich geschrieben werden. Auch können Wir sie als python notebooks schreiben (siehe branch 'dev-tests-ipynb'

**Comment by baumbude** [comment]
Hi,
Na klar, die Test sind ja aktuell auch nur ein Test der Beispiele, und
nicht mehr, aber die examples sollten weiterhin mitgetestet werden.

So kann ein Testordner mal aussehen:
https://github.com/oemof/oemof-solph/tree/dev/tests

Notebooks find ich sehr gut. Vlt sind sie aber für manchen auch eine Hürde?

Gruß

Felix


Dr.-Ing. Felix Panitz
Am Hang 2
02689 Wehrsdorf
Tel.: 01577 2962394
E-Mail: ***@***.***

FBumann ***@***.***> schrieb am Sa., 25. Mai 2024, 17:09:
