### ISSUE TITLE
Transmission

### ISSUE THREAD

**Issue by FBumann** [flixOpt/flixOpt#59]
Add the class Transmission back into flixOpt

**Comment by FBumann** [comment]
Auf jeden fall in den release.
Aktueller stand passt

**Comment by baumbude** [comment]
Hab es mir nochmal angeschaut. Sollte so erstmal passen. Eine Grundfunktionalität ist da (insbesondere Begrenzung des Durchfluss für bestehende Leitung und Investentscheidungen für neue Verbindungsleitung). 
Alle weitere Funktionalität ist auch nicht schnell gemacht. Da gibt es einige grundlegende Fragen erstmal zu klären.
Also gerne mergen

**Comment by FBumann** [comment]
Closed with #89
