### ISSUE TITLE
Interface for HiGHS solver is created via Pyomo

### ISSUE THREAD

**Issue by FBumann** [flixOpt/flixOpt#7]
Implement and test the interface for promo for HiGHS

**Comment by FBumann** [comment]
Implement and test the interface for promo for HiGHS

**Comment by FBumann** [comment]
Not all parameters are available (current assumption)
gapFrac, timelimit

**Comment by PStange** [comment]
- Highs is working, gapFrac and timelimit can be used
current restrictions:
- number of threads is fixed to 4 and solver log-file is written in "results/Highs.log" in the first stage of integration
- "live" solver output to console not working right now

**Comment by FBumann** [comment]
Highs in dependencies ?

**Comment by FBumann** [comment]
Ready to merge

**Comment by FBumann** [comment]
Test did not work well.
pip install highspy does not include the solver itself it seems like...
@PStange
