### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by FBumann** [flixOpt/flixOpt#83]

**Comment by FBumann** [comment]
Abschnitt solver überarbeiten.
Plot von einem Bus mit rein.
Netzwerkgrafik mit rein.
Evtl. heatmap mit rein.

**Comment by PStange** [comment]
Mir sind halt Tippfehler erst später aufgefallen und ich mag es öfter zu „speichern“. Ich mache da auch noch weiter bzgl. Grafiken. 

Ist das nicht egal, wie viele commits das sind? Die readme ist doch sowieso losgelöst vom Rest.

 

Von: FBumann ***@***.*** 
Gesendet: Montag, 9. Dezember 2024 17:21
An: flixOpt/flixOpt ***@***.***>
Cc: Stange, Peter ***@***.***>; Mention ***@***.***>
Betreff: Re: [flixOpt/flixOpt] Update the Readme (Issue #83)

 

@PStange <https://github.com/PStange> 
Wäre cool wenn wir das nächstes mal nie einem commit schaffen.
Oder du machst es in einem extra branch, dann kann man die im Nachhinein zusammenfassen.

**Comment by FBumann** [comment]
Ja stimmt schon
Da sollte es eigentlich keine Probleme mit dem merge geben...

**Comment by FBumann** [comment]
Closed with #109
