### ISSUE TITLE
decrease default size to avoid numerical issues

### ISSUE THREAD

**Issue by FBumann** [flixOpt/flixOpt#86]
Currently, the default size of a Flow is 1e9.
This leads to a bunch of warnings, resulting from constraints with binary variables and big numbers.
This behaviour is not nice, as its leads to uncertainty for new users and also to real numerical problems...
I would prefer if we decrease the default value to 1e5 or something like that.
The value is to be discussed...
It should be high enough to not restrict Sources and Sinks all the time, but low enough to not lead to numerical issues.

**Comment by PStange** [comment]
Das Problem ist klar und schon aus rein numerischer Sicht, wäre mir eine kleinere Schranke auch lieber. Allerdings ist das wirklich schwierig und sollte per default nicht zu klein sein. Das kann zu nicht so einfach zu erkennenden, ungewollten Ergebnissen führen. Wenn man beispielsweise Schranken für Jahressummen von irgendetwas hat, kommt man auch mal schnell mal über den 1e5 Bereich, auch wenn andere Werte sich eher um die 10 - 1000 bewegen. 
Eine saubere, aber evtl. umständliche Variante wäre, alle Nebenbedingungen durchzugehen und festzustellen welche Parameter man ins Verhältnis zum jeweiligen bigM setzten muss. Dies könnte wahrscheinlich automatisch im Preprocessing geschehen und das bigM möglichst klein wählen. 

Bei den ganzen Überlegungen sollte man im Hinterkopf behalten, dass wir aus double-Sicht 16 relevante Stellen zur Verfügung haben. Das heißt, wenn in einer Gleichung ein 1e9 als größter Wert auftritt, sollte nichts kleiner sein als 1e-7 (Besser vielleicht 1e-6 oder 1e-5, um etwas Puffer zu haben. Was der Löser intern mit den Zahlenwerten tut, ist uns ja nicht so 100% klar - aber Gurobi, Highs und was wir so nutzen, sollte schon recht stabil sein). 
Solange man sich daran hält, sollte numerisch nichts passieren.

**Comment by FBumann** [comment]
Wenn möglich Obergrenze 1e7 für Binärvariablen.
Umsetzung noch unklar.
v1.1 reicht

**Comment by FBumann** [comment]
Global variable for use in different places.
1e7

**Comment by FBumann** [comment]
Closed with #102
