### ISSUE TITLE
Heatmap error with plotly 5.13.1

### ISSUE THREAD

**Issue by dizont** [flixOpt/flixOpt#88]
In requirements plotly >= 5.9.0 ist nicht ganz korrekt. Mit 5.13.1 ich kriege den Error:

`ValueError: Invalid property specified for object of type plotly.graph_objs.heatmap.ColorBar: 'xref'`

In 5.13.1 es gibt noch kein xref, yref properties für ColorBar. Es gibt sie erst in späteren Versionen.

**Comment by FBumann** [comment]
Hi,
Danke für die Anmerkung.
Kannst du mir noch mitteilen welche Funktion du genutzt hast?
Wir arbeiten grade an einem neuen Release (dev-branch).
Nutzt du das schon oder die aktuelle Version (Main)?

**Comment by dizont** [comment]
Das war in allen Beispielen wie

`results.plot_operation('CHP__Q_th', 'heatmap')`

**Comment by FBumann** [comment]
Super.
Habs gefixt. Geht ab v5.15 [plotly releases](https://github.com/plotly/plotly.py/releases?page=2)
commit 2fbb3576a70eee148a30c86d0e3f3e645646c15a
